%% 1.test_inertial_solve
mex -R2018a -output test_inertial_solve...
./C_code/test_inertial_solve.c...
./C_code/axes.c...
./C_code/matrix_operation.c...
./C_code/inertial_solve.c

%% 2.test_transfer_alignment
mex -R2018a -output test_transfer_alignment...
./C_code/test_transfer_alignment.c...
./C_code/axes.c...
./C_code/inertial_solve.c...
./C_code/matrix_operation.c...
./C_code/transfer_alignment.c